web_themes/base/1_root.css
web_themes/full/5_game_details.css

On some accounts, the Play button is a segmented control with a dropdown menu (eg. Steam Link). This PR handles that case.
Also, it seems to me that some elements are using the card_radius variable where they should be using the button_radius var. I've fixed that for this very obvious button, but it's possible some other elements might require that change too.

Web full: Game details - Play button, streaming device

---

install.py

Match was introduced in 3.10, but some environments are still shipping 3.9.
Notably, Debian and flatpak's `org.gnome.Platform` do this, the latter of which affects my attempts at a [frontend](https://github.com/Foldex/AdwSteamGtk) using that runtime as I can't simply use the installer included in the release zip.
Currently I'm supplying a patched version of the installer, but obviously it's not ideal to do so.
As a side note: The frontend only downloads the latest release, so this won't effectively kick in until a new release is made.

Installer: Fix for Python 3.9

---

patches/windowcontrols/left-all.patch

fixes left-all to be consistent with gnome's left align window controls, which go in the order left to right of "close, minimise, maximise" instead of "close, maximise, minimise".

`windowcontrols/left-all`: match gnome-tweaks' left preset

---

install.py

Just makes the error more clear to users trying to run `patch` when it isn't installed.

Installer: Ensure patch is installed (#32, Fixes #27)

---

install.py
patches/windowcontrols/hide-close.patch
web_themes/extras/windowcontrols/hide-close.css
web_themes/extras/windowcontrols/right-all.css
web_themes/full/7_dialogs.css

This fixes #51 and partially addresses #56
Window control patches get shared with a corresponding web extra, so you only have to pass:
`-p windowcontrols/hide-close` instead of having to specify both `-p` and `-we` to get the desired effect.
Currently this is limited to `right-all` and `hide-close` as they don't require shifting layout for the web controls. Left style WCs will  likely be another PR.

Web Full: Window controls patches (Fixes #51)

---

Adwaita/resource/layout/playersdialog.layout
Adwaita/resource/steamscheme.res

My previous pull request (#39) caused issue #70, by making frame_close visible for PropertyDialog in steamscheme.res. This pull request hides it again and places the OKButton for playersdialog instead. The OK button in the overlay settingsdialog is moved back to the right.

Change playersdialog close button

---

extras/patches/windowcontrols/left-all.patch
extras/patches/windowcontrols/left.patch
extras/web/extras/windowcontrols/left-all.css
extras/web/extras/windowcontrols/left.css
install.py

Adds support for left aligned window control patches to affect the web based parts of the interface (#56, #84, #85).
Additionally adds support for the VGUI news dialog to the existing patches (#87)
Currently affects App Properties, Chat, Friend List Settings, and Content Management dialogs. I'm not aware of any other web based dialogs that have window controls.
The `All` patch for web stuff is a bit limited, it only shows controls that exist but were hidden by the default web theme; I can't add controls that don't already exist.

Left window controls fixes

---

install.py

Well it's worse than what we had before, but not much of a choice.
Adds steam patching ala SFP to the installer, which will get the library theming working again.
This does mean a reinstall will have to be performed on client update, unless we want to make the installer have an option to run in the background and watch for file changes. I think the graphical installer would be a better place for something like that though.
This has some bits for chat patching too, but as that still works for the moment I've left it as is.
Moving forward we'd probably want to do something cleaner and have chat/library specific css files rather than the monolithic `webkit.css`, but shrug.

Installer: Patch Steam Library Files (Fixes #113, #119)

---

install.py

Fixes an issue where the `libraryroot.custom.css` file would not be overwritten if `steamui/library.css` had already been patched.

Installer: Always Overwrite library.custom.css on install

---

extras/web/extras/library/sidebar_hover.css

Adds a web extra to only show the sidebar on hover.
Might add some UX finickiness, but as an optional extra it's probably fine.
Originally wanted to have `:focus-within` also expand the sidebar, but as steam starts with it focused anyway and likes to reset focus back to it when switching views, it wound up too annoying.
Resizing the sidebar can also be a bit pixel perfect when this is active, but shrug.

Web Extra: Add Library Sidebar Hover

---

README.md
extras/web/README.md
extras/web/base/collections.css
extras/web/base/dialogs/launch_options.css
extras/web/base/dialogs/login.css
extras/web/base/downloads.css
extras/web/base/game_details.css
extras/web/base/library.css
extras/web/full/dialogs/_dialogs.css
extras/web/full/dialogs/app_properties.css
extras/web/full/dialogs/content_management.css
extras/web/full/dialogs/friends_settings.css
extras/web/full/dialogs/paged_settings.css
extras/web/full/dialogs/whats_new.css
extras/web/full/downloads.css
extras/web/full/game_details.css
extras/web/full/library.css

Decent amount of selector changes, partially to avoid theming Big Picture, partially a general cleanup.
Steam provides a useful node ID for avoiding this:
```css
#SteamDesktop
```
But as it isn't a top level node, tooltips and other hover elements that like to get injected as a direct child of `body` will bypass this. For these we have to resort to using a `:not()` selector on the body class itself.
```css
body:not([class*="gamepadui_GamepadUIPopupWindowBody_"])
```
Did a bit of cleanup to avoid straight up using:
```css
[class*="etc_etc"]
```
type selectors. Now most selectors include the tag of the element they're targeting:
```css
span[class*="etc_etc"]
```
Which should at least be a slightly less blatant abuse of wildcard selectors. Moving forward we should avoid tagless selectors …

Web Theme: Refine Selectors (Fixes #132)

---

web/extras/topbar/vanilla_bar.css

The show arrows extra makes some changes designed for the Adwaita style headerbar, which interacts poorly when the vanilla style bar was enabled.
This fixes that interaction, ensuring the vanilla bar extra looks correct even with show arrows enabled.

Web Extras: Fix interaction between vanilla_bar and show_arrows

---

web/extras/general/no_rounded_corners.css

Applies a 1px radius instead of 0px. Pretty much the same and maintains the not rounded look, just slightly less harsh.
Also adds the new `--icon_small_radius` variable

Adjust No Rounded Corners

---

web/base/top_bar.css

Super Nav seems to have had a change that caused longer items to wrap rather than use text-overflow.
Disables wrapping so we properly hit ellipses.

Web Base: Fix Top Bar Nav Wrapping

---

adwaita/variants/base/main_window/headerbar/buttons.css

Reorders/Resizes the Avatar button so that it is more in line with the rest of the headerbar. Before it was a bit oversized, and was cutting between the notification button and similar button elements.
This does involve using:
```css
div.Focusable:nth-child(3)
```
Which is not ideal, but probably shouldn't be an issue unless the layout changes.

Headerbar: Avatar size/order changes

---

theme.json

This allows the theme to be loaded through CSS Loader. Loading through CSS Loader also resolves the Steam Big Picture injection issue.

Add CSS Loader config to repository

---

theme.json

I'm pretty sure that there isn't a way to use custom css when under CSS Loader, so I added one to my local copy.

Add option to use custom.css on CSS Loader

---

install.py

Fixes the unexpected behaviour on Windows that causes the `args.target` always to be overwritten, effectively disabling the `--target` argument on Windows and requiring manual edits to the constants to change the target destination path.
This PR also changes the default behaviour on non-Windows systems, so that default values are no longer being strictly enforced when additional or explicit parameter values have been given for the `--target` argument.
1. Call `install.py` with the `--target` argument on Windows and supply a custom path.
2. Output the contents of `args.target`.
3. The supplied custom path was lost, defaulting to the value `windows`.
1. Same steps as for the reproduction.
2. On non-Windows systems:
2.1. Do not specify the `--target` argument.
2.2. This will default to the …

Fix: Do not overwrite args.target on Windows if value is set

---

install.py

The install script may wrong on Windows with encoding error `UnicodeEncodeError: 'cp950' codec can't decode...`
#286

fix: Encoding error on Windows

---

adwaita/css/widgets/popups.css

||Before|After|
|-|-|-|
|Friends menu|![Friends menu before](https://github.com/user-attachments/assets/b6687988-5f15-40ce-8e8c-0b77491fa3be)|![Friends menu after](https://github.com/user-attachments/assets/16a596b0-faf7-4c8e-80bd-05147996f435)|
|Account menu|![Account menu before](https://github.com/user-attachments/assets/06ddf299-87d6-44bc-ba45-7eeeee681905)|![Account menu after](https://github.com/user-attachments/assets/cf062602-5ac8-4478-ae9c-01b4890ae662)|

Fix some menu item text wrapping.
