- web_themes/full/3_library.css
> Web Full: Rounded New to Library (Fixes #66)

- web_themes/base/10_new_login.css
- web_themes/base/1_root.css
> Web Base: Login Checkbox Fix

- web_themes/base/10_login.css
- web_themes/base/1_root.css
- web_themes/full/7_dialogs.css
[2022-10-14_23-39-02-[00.00.000-00.29.909].webm](https://user-images.githubusercontent.com/47908676/195967437-7a926bb9-a279-4941-a15d-540581e8b045.webm)
Mostly focused on theming the app properties window, but some rulesets are fairly general to Dialogs. I haven't noticed any breakages, and they seem to be applying fine in other dialogs like Friends List settings (which I believe is the last dialog left to do).
> Web Full: Dialog & App Properties Fixes

- install.py
Think the full theme is in a good enough state at this point.
> Installer: Make Web Full Theme the Default

- Adwaita/resource/layout/accountmenu.layout
Fixing account menu to prevent button overlap and improving the visibility of the account name.
> Account menu improvements

- install.py
It is possible to force the steam client to reload the theme by creating a uniquely named new file inside the steamui dir.
This only seems to work when Steam is run with the -dev arg, and reloading repeatedly can leak a lot of memory.
Still, this is fairly useful for testing changes.
> Installer: Add hot reload

- web/base/_root.css
- web/full/library.css
> Web Full: Library Sidebar Rounded Square Icons

- web/full/dialogs/app_properties.css
New option added to app properties.
> Web Full: App Properties Overlay Data Fix

- scripts/update_classes.sh
- web/base/library.css
> Small Mode Fix

- colorthemes/catppuccin-frappe/catppuccin-frappe.theme
- colorthemes/catppuccin-macchiato/catppuccin-macchiato.theme
- colorthemes/catppuccin-mocha/catppuccin-mocha.theme
- colorthemes/dracula/dracula.theme
- colorthemes/nord/nord.theme
- colorthemes/one-pro/one-pro.theme
- colorthemes/pop/pop.theme
- colorthemes/tomorrow-night/tomorrow-night.theme
- web/base/_root.css
- web/base/dialogs/login.css
- web/base/library.css
- web/full/game_details.css
- web/full/library.css
> Web/Themes: Fix accent_fg and success_fg contrast

- web/full/dialogs/install_game.css
Installing SteamVR had messed up button placement.
> Web Full: InstallRequestModal fix

- README.md
> Readme: Update

- web/extras/topbar/hide_vr.css
> Web Extra: Hide VR Button

- install.py
Fixes https://github.com/Foldex/AdwSteamGtk/issues/42
The installer would move the generated libraryroot into the first install target, causing the second install target to fail.
Also moves uninstall logic out of `patch_client_css()`, into its own function.
> Installer: Fix Multiple Targets

- adwaita/variants/full/dialogs/app_properties.css
- custom/custom.css
Closes https://github.com/Foldex/AdwSteamGtk/issues/44
Includes some other small fixes to App properties
> App properties fixes

- adwaita/variants/base/library.css
> Library: Gamelist HoverOverlay Fix

- adwaita/variants/full/dialogs/update_news.css
- install.py
Closes: https://github.com/Foldex/AdwSteamGtk/issues/48
> Update News: Fix Headerbar

- .gitignore
config_USER.json is created by CSS Loader when changing theme settings. Useful for auto-updating the theme via git for CSS Loader so long as it's not on their store.
> Add config_USER.json to gitignore

- adwaita/variants/full/dialogs/app_properties.css
> App Properties: Fix Updates Dropdowns

- adwaita/variants/base/_localization.css
I added Spanish, French, Italian and Portuguese
> Localization: Add more languages

- adwaita/css/main/library/collections/collections.css
- adwaita/css/main/library/downloads/downloads.css
- adwaita/extras/login/hide_qr.css
- install.py
- theme.json
Just putting up notice for this, likely will just wait for #281 to be merged.
Fixes the completely unstyled bits of Collections/Downloads.
Also includes a fix for the hide_qr extra.
> Downloads/Collections Support

- adwaita/css/main/headerbar/headerbar.css
- adwaita/css/main/library/details/activity.css
- adwaita/css/main/library/details/details.css
- adwaita/css/main/library/details/header.css
- adwaita/css/main/library/home/home.css
- adwaita/css/main/library/sidebar/sidebar.css
- adwaita/css/widgets/popups.css
> Small fixes and improvements
